- hosts: node
  tasks:
    - name: Create new deployment
      command: kubectl apply -f  /home/ubuntu/deployment.yaml

    - name: Create new service
      command: kubectl apply -f  /home/ubuntu/service.yaml
    
    - name: Port forwarding 
      command: kubectl port-forward svc/my-app-service 30001:3000
